apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    tier: backend
    app: node
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
      app: node
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        tier: backend
        app: node
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: world-of-chatting-secrets
          env:
            - name: APP_PORT
              value: '3000'
            - name: LOAD_CONFIG_FILE
              value: 'false'
            - name: DB_SERVICE_SERVICE_PORT
              value: '5432'
          name: api
          image: dscr.io/slevine111/worldofchatting
          ports:
            - containerPort: 3000
      initContainers:
        - name: init-redis
          image: busybox:1.28
          command:
            [
              'sh',
              '-c',
              'until nslookup redis-service; do echo waiting for redis; sleep 2; done;',
            ]
        - name: init-postgres
          image: busybox:1.28
          command:
            [
              'sh',
              '-c',
              'until nslookup db-service; do echo waiting for db; sleep 2; done;',
            ]
