apiVersion: v1
kind: Secret
metadata:
  name: world-of-chatting-secrets
data:
  DB_SERVICE_SERVICE_HOST: ENV-VAR-DB-SERVICE-SERVICE-HOST
  DATABASE_NAME: ENV-VAR-DATABASE-NAME
  POSTGRES_USER: ENV-VAR-POSTGRES-USER
  POSTGRES_PASSWORD: ENV-VAR-POSTGRES-PASSWORD
  REDIS_PASSWORD: ENV-VAR-REDIS-PASSWORD
  JWT_SECRET: ENV-VAR-JWT-SECRET
