version: '3'
services:
  api:
    build: .
    image: slevine111/worldofchatting_api
    container_name: worldofchatting_api
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - HOST=my_postgres
      - PORT_DATABASE=5432
      - PORT=3000
      - USERNAME=postgres
      - DATABASE=world_of_chatting
      - DATABASE_TEST=world_of_chatting_test
    volumes:
      - './:/user/src/app'
      - 'node_modules:/user/src/app/node_modules'
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    container_name: my_postgres
    ports:
      - '54320:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=world_of_chatting
    volumes:
      - 'dbdata:/var/lib/postgresql/data'

volumes:
  dbdata:
  node_modules:
