FROM node:lts-alpine AS build
RUN apk --no-cache add --virtual builds-deps build-base python
WORKDIR /user/src/app
COPY ./package*.json  ./
RUN npm audit
RUN npm install

FROM node:lts-alpine
WORKDIR /user/src/app
#RUN mkdir node_modules public js
COPY --from=build  /user/src/app/node_modules ./node_modules
COPY tsconfig.json package.json  ormconfig.js index.html webpack.config.js ./
COPY ./@types ./@types
COPY ./src ./src
RUN npm run tsc
EXPOSE 3000
CMD ["npm","run","start:dev"]
