FROM node:lts-alpine AS build-and-test
RUN apk --no-cache add --virtual builds-deps build-base python
WORKDIR /user/src/app
COPY ./package*.json  ./
#RUN npm audit
RUN npm install
COPY tsconfig.json package.json jest.config.js ormconfig.js jest-global-setup.ts jest-global-teardown.ts ./
COPY ./@types ./@types
COPY ./src ./src
COPY ./tests ./tests

FROM node:lts-alpine AS dev
WORKDIR /user/src/app
COPY --from=build-and-test  /user/src/app/node_modules ./node_modules
COPY tsconfig.json package.json  ormconfig.js index.html webpack.config.js ./
COPY ./@types ./@types
COPY ./src ./src
COPY ./js ./js
EXPOSE 3000
CMD ["npm","run","start:dev"]
