version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile-test
    container_name: worldofchatting-webserver-test
    environment:
      - DB_SERVICE_SERVICE_HOST=db
      - REDIS_SERVCE_SERVICE_HOST=redis
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_TEST=${POSTGRES_USERNAME}
      - JWT_SECRET_TESTING=${JWT_SECRET_TESTING}
    depends_on:
      - db
      - redis
  db:
    image: postgres:11-alpine
    container_name: worldofchatting-db-test
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis:
    image: redis:5-alpine
    container_name: redis-db-test
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
