apiVersion: skaffold/v1beta13
kind: Config
metadata:
  name: world-of-chatting-app
build:
  artifacts:
    - image: slevine1893/worldofchatting
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
