apiVersion: skaffold/v1beta17
kind: Config
metadata:
  name: world-of-chatting-app
build:
  tagPolicy:
    dateTime: {}
  artifacts:
    - image: worldofchattingdev
      sync:
        infer:
          - 'tsconfig.json'
          - 'index.html'
          - 'webpack.config.js'
          - 'ormconfig.js'
          - 'package.json'
          - 'node_modules/**'
          - 'src/**'
          - 'public'
      docker:
        dockerfile: Dockerfile-dev
  local: {}
deploy:
  kubeContext: minikube
  kubectl:
    manifests:
      - k8s-common/*.yaml
      - k8s-dev/*.yaml
