apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: db-service
subsets:
  - addresses:
      - ip: '10.0.2.2'
    ports:
      - port: 5432
