apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/mnt/data/postgresql'
