apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    tier: backend
    app: node
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
      app: node
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        tier: backend
        app: node
    spec:
      containers:
        - env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: world-of-chatting-secrets
                  key: JWT_SECRET
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: world-of-chatting-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: world-of-chatting-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: world-of-chatting-secrets
                  key: POSTGRES_PASSWORD
          name: api
          image: dscr.io/slevine111/worldofchatting
          ports:
            - containerPort: 3000
