apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    tier: backend
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      app: redis
  template:
    metadata:
      labels:
        tier: backend
        app: redis
    spec:
      containers:
        - name: db
          image: redis:5.0
          ports:
            - containerPort: 6379
