apiVersion: v1
kind: Servicedsfgbhgsdesfdgh
metadata:
  name: api-service
  labels:
    tier: backend
    app: node
spec:
  selector:
    app: node
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
