apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    tier: backend
    app: redis
spec:
  selector:
    tier: backend
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
