export const SET_MY_USER_CHAT_GROUPS = <const>'SET_MY_USER_CHAT_GROUPS'
export const SET_CURRENT_LANGUAGE_USER_CHAT_GROUPS = <const>(
  'SET_CURRENT_LANGUAGE_USER_CHAT_GROUPS'
)
export const SET_MY_AND_CURRENT_LANGUAGE_USER_CHAT_GROUPS = <const>(
  'SET_MY_AND_CURRENT_LANGUAGE_USER_CHAT_GROUPS'
)
