export const INITIAL_SUBGROUPING_KEYS = <const>{
  users: {
    NO_DIRECT_CHAT_WITH_KEY: 'NO_DIRECT_CHAT_WITH_KEY',
  },
  userLanguages: {
    LOGGED_IN_USER_SUBGROUPING_KEY: 'LOGGED_IN_USER_SUBGROUPING_KEY',
  },
  chatGroups: {
    FAVORITE_CHAT_GROUPS_KEY: 'FAVORITE_CHAT_GROUPS_KEY',
    CHAT_GROUPS_WITH_MESSAGES_KEY: 'CHAT_GROUPS_WITH_MESSAGES_KEY',
    CHAT_GROUPS_NO_MESSAGES_KEY: 'CHAT_GROUPS_NO_MESSAGES_KEY',
    CHAT_GROUPS_NOT_SEEN_LAST_MESSAGE_KEY:
      'CHAT_GROUPS_NOT_SEEN_LAST_MESSAGE_KEY',
  },
  notifications: { NOT_SEEN: 'NOT_SEEN' },
}

export const CHAT_GROUP_KEY_PREFIX = <const>'chatGroup'
