/** Declaration file generated by dts-gen */

declare module 'volleyball' {
  function volleyball(req: any, res: any, next: any): any

  const prototype: {}

  function custom(...args: any[]): any

  namespace custom {
    const prototype: {}
  }
}
