export const LOGOUT_USER_PROCESS = <const>'LOGOUT_USER_PROCESS'
export const USER_LOGGED_IN = <const>'USER_LOGGED_IN'
export const WENT_TO_LANGUAGE_PAGE_VIEW = <const>'WENT_TO_LANGUAGE_PAGE_VIEW'

export const REQUEST_DATA_API = <const>'REQUEST_DATA_API'
export const REQUEST_DATA_SUCCESS_API = <const>'REQUEST_DATA_SUCCESS_API'
